#!/usr/bin/env node
// The GameDistribution self-hosted wrapper page.
//
// GameDistribution normally hosts the uploaded build. For a self-hosted game the README
// ("Implementation self-hosted games", https://github.com/GameDistribution/GD-HTML5) says:
//
//   "they will have to upload a zipped index.html-file containing an iframe with the
//    following query variable: GD_SDK_REFERRER_URL. The value of this variable should be the
//    parentUrl. A perfect example can be found at ./index_iframe.html."
//
// This writes that index.html. It follows index_iframe.html (GD-HTML5 at 4873abe) line for
// line in what it computes — the embedding page's URL, taken from document.referrer when the
// wrapper is itself framed, an incoming gd_sdk_referrer_url passed through, localhost mapped
// to https://gamedistribution.com/ as the example does — with two corrections that change no
// value the SDK receives: the referrer is URL-encoded (the example concatenates it raw, so a
// referrer with its own query string would be cut at its first "&"), and the parameter is
// appended with URL's searchParams so a game_url that already has a query stays valid.
//
// The referrer is computed at run time, in the wrapper, from wherever GameDistribution's
// publishers embed it. It is never baked in: a fixed value would report every embed as one
// page. The game itself sets nothing — the GD SDK reads the parameter from its own URL.
//
// Usage:
//   node scripts/release/gamedistribution-wrapper.mjs --game-url https://games.example.com/g/ \
//     [--out build/gamedistribution/self-hosted/index.html]

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { isEntryPoint, parseArgs, repoRoot } from "../_shared.mjs";

/** The https URL the self-hosted game is served from, validated as game.config.yaml does. */
export function checkGameUrl(gameUrl) {
  let url;
  try {
    url = new URL(gameUrl);
  } catch {
    throw new Error(`game_url must be an absolute URL, got ${JSON.stringify(gameUrl)}`);
  }
  if (url.protocol !== "https:") throw new Error(`game_url must be https, got ${url.protocol}`);
  for (const key of url.searchParams.keys()) {
    if (key.toLowerCase() === "gd_sdk_referrer_url") {
      throw new Error("game_url must not carry gd_sdk_referrer_url; the wrapper sets it");
    }
  }
  return url.href;
}

export function wrapperHtml(gameUrl) {
  const href = checkGameUrl(gameUrl);
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>GameDistribution self-hosted game wrapper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <style>
      html { height: 100%; }
      body { margin: 0; padding: 0; height: 100%; overflow: hidden; }
      #container {
        position: absolute; top: 0; left: 0; width: 0; height: 0; overflow: hidden;
        max-width: 100%; max-height: 100%; min-width: 100%; min-height: 100%;
        box-sizing: border-box; border: 0;
      }
    </style>
  </head>
  <body>
    <iframe id="container" allow="autoplay" allowfullscreen scrolling="no"></iframe>
    <script>
      // Generated by scripts/release/gamedistribution-wrapper.mjs from GameDistribution's
      // index_iframe.html. See docs/platforms/gamedistribution.md, "Self-hosting".
      (function () {
        function param(url, name) {
          try {
            var params = new URL(url).searchParams;
            var found = null;
            params.forEach(function (value, key) {
              if (key.toLowerCase() === name) found = value;
            });
            return found;
          } catch (e) {
            return null;
          }
        }
        function referrerUrl() {
          var parentUrl = document.location.href;
          if (window.location !== window.parent.location && document.referrer) {
            parentUrl = document.referrer;
          }
          if (document.referrer.indexOf("localhost") !== -1) {
            parentUrl = "https://gamedistribution.com/";
          }
          return param(parentUrl, "gd_sdk_referrer_url") || parentUrl;
        }
        var game = new URL(${JSON.stringify(href)});
        game.searchParams.set("gd_sdk_referrer_url", referrerUrl());
        document.getElementById("container").src = game.href;
      })();
    </script>
  </body>
</html>
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (typeof args["game-url"] !== "string") {
    console.error("usage: gamedistribution-wrapper.mjs --game-url https://... [--out <path>]");
    process.exit(2);
  }
  const out = resolve(
    repoRoot(),
    typeof args.out === "string" ? args.out : "build/gamedistribution/self-hosted/index.html",
  );
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, wrapperHtml(args["game-url"]));
  console.log(`wrote ${out}`);
}

if (isEntryPoint(import.meta.url)) main();
