// The build target's adapter, and only that one.
//
// `virtual:target-platform` is generated by scripts/build/game-config-plugin.ts for the
// platform the build is for, and imports that adapter's subpath of @wgf/platform-sdk alone.
// createPlatform in the package's registry references every adapter — fine for tests and
// tools, but a bundle that called it would carry every portal's SDK loader and URL, which the
// portal profiles reject as foreign SDKs.

import type { CreatePlatformOptions, Platform } from "@wgf/platform-sdk";
import { TARGET_PLATFORM_ID, createTargetPlatform as create } from "virtual:target-platform";

/** The id of the platform this bundle was built for. */
export const targetPlatformId: string = TARGET_PLATFORM_ID;

/** Constructs the build target's adapter. Pass platformOptions(targetPlatform()). */
export function createTargetPlatform(options: CreatePlatformOptions): Platform {
  return create(options);
}
